[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=/home/rvnchki/foundry-f23/foundry-fund-me-f23/lib/chainlink-brownie-contracts/contracts/",
    "chainlink-brownie-contracts/=/home/rvnchki/foundry-f23/foundry-fund-me-f23/lib/chainlink-brownie-contracts/",
    "forge-std/=/home/rvnchki/foundry-f23/foundry-fund-me-f23/lib/forge-std/src/",
    "foundry-devops/=/home/rvnchki/foundry-f23/foundry-fund-me-f23/lib/foundry-devops/",
]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
